import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [{type: 'autogenerated', dirName: '.'}],
  ledger: [{type: 'autogenerated', dirName: 'ledger'}],
  payments: [{type: 'autogenerated', dirName: 'payments'}],
  integrations: [{type: 'autogenerated', dirName: 'integrations'}],

  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
